version: '3.8'

services:
  # Nginx service
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web

  # Django web application
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./envs/.auth.env
    volumes:
      - ./:/app
      - ./static:/app/static
      - ./media:/app/media

  # PostgreSQL Database
  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=storedb
    ports:
      - "5432:5432"

volumes:
  postgres_data:
